language: ruby
rvm:
  - 2.2.2
branches:
  only:
  - master
gemfile:
  - mw/Gemfile
services:
  - redis-server
  - postgresql
before_script:
  - cp ./database.yml.travis mw/config/database.yml
  - cd mw
  - psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rake RAILS_ENV=test
addons:
  code_climate:
    repo_token: 94869ed440cfcde7ea06a4458b35dd6ad74590d6f188d13969a14014c93166e8
after_success:
  - cd mw && bundle exec codeclimate-test-reporter