language: ruby
rvm:
  - 2.2
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 94869ed440cfcde7ea06a4458b35dd6ad74590d6f188d13969a14014c93166e8
after_success:
  - bundle exec codeclimate-test-reporter