source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use Puma as the app server
gem 'puma', '~> 3.0'

# User Authentication
gem 'devise', '~> 4.2'
gem 'tiddle', '~> 1.0'

# Handle Ruby CORS
gem 'rack-cors', '~> 0.4.0'

# Faker for generating test data
gem 'faker', '~> 1.6', '>= 1.6.6'

# Database
gem 'pg', '~> 0.19.0'

# Redis for Caching
gem 'redis-rails', '~> 5.0', '>= 5.0.1'

# Serializer
gem 'active_model_serializers', '~> 0.10.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :test do
  gem 'rake', '~> 12.0'
  gem 'simplecov', '~> 0.12.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.1'
  gem 'webmock', '~> 2.3', '>= 2.3.1'
  gem 'codeclimate-test-reporter', '~> 1.0.0'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
